import { webcrypto } from "node:crypto";

import type { ValidatorEncrypter } from "../../application/ports/out/validator-encrypter.port.ts";
import { KeyValidatorBlob } from "../../domain/value-objects/key-validator-blob.ts";
import type { MasterKey } from "../../domain/value-objects/master-key.ts";
import { AeadFailedError } from "../errors/aead-failed-error.ts";

const AES_GCM_TAG_LENGTH_BITS = 128;
const AES_GCM_TAG_LENGTH_BYTES = AES_GCM_TAG_LENGTH_BITS / 8;
const AES_GCM_NONCE_LENGTH_BYTES = 12;

/**
 * Adapter that fulfils the `ValidatorEncrypter` application port
 * using Node 20+ Web Crypto AES-256-GCM (`node:crypto` `webcrypto`).
 *
 * The adapter is the WRITE-side counterpart of `AesGcmKeyValidator`:
 * it encrypts a sentinel under the master key at init/rekey time so
 * that, at unlock time, the validator can confirm a candidate key
 * decrypts the same sentinel without opening the SQLCipher database
 * (`docs/11-seguridad-modos.md` §7).
 *
 * Why a separate adapter (not folded into `AesGcmEnvelopeCipher`):
 * - The envelope cipher is shape-pinned to wrap a 32-byte master
 *   key with a 32-byte derived key. The validator path encrypts an
 *   arbitrary-length sentinel (typically 18 bytes for
 *   `"VALID-WORKSPACE-V1"`). Reusing the envelope cipher would
 *   require either padding (couples the two flows) or broadening
 *   the envelope contract (hurts ISP). The dedicated adapter is the
 *   cleanest split.
 *
 * Output shape:
 * - `subtle.encrypt(...)` returns a single `ArrayBuffer` containing
 *   `ciphertext || tag`. The adapter splits the trailing
 *   `AES_GCM_TAG_LENGTH_BYTES` into `tag` and the rest into
 *   `ciphertext` so the resulting `KeyValidatorBlob` matches the
 *   domain VO's quad-buffer shape.
 *
 * Security invariants:
 * - The adapter NEVER logs ciphertext, tag, IV, master key bytes or
 *   plaintext.
 * - The IV is freshly generated by Node's CSPRNG on every call.
 *   Reusing an IV under the same key on AES-GCM catastrophically
 *   compromises confidentiality + authenticity.
 * - The plaintext buffer copy is zero-filled after the encrypt call.
 */
export class AesGcmValidatorEncrypter implements ValidatorEncrypter {
  public async encrypt(input: {
    masterKey: MasterKey;
    plaintext: Uint8Array;
  }): Promise<KeyValidatorBlob> {
    if (!(input.plaintext instanceof Uint8Array)) {
      throw AeadFailedError.invalidBufferSize("plaintext", 1, 0);
    }
    if (input.plaintext.length === 0) {
      throw AeadFailedError.invalidBufferSize("plaintext", 1, 0);
    }

    const subtle = getSubtle();
    const iv = generateNonce();

    const cryptoKey = await input.masterKey.withBytes((bytes) =>
      importMasterKey(subtle, bytes),
    );

    // Defensive copy: the ports' `encrypt` API takes a borrowed
    // `Uint8Array` and the adapter must not mutate the caller's
    // buffer.
    const plaintextCopy = new Uint8Array(input.plaintext);

    let combined: ArrayBuffer;
    try {
      combined = await subtle.encrypt(
        {
          name: "AES-GCM",
          iv,
          tagLength: AES_GCM_TAG_LENGTH_BITS,
        },
        cryptoKey,
        plaintextCopy,
      );
    } catch (cause: unknown) {
      plaintextCopy.fill(0);
      throw AeadFailedError.libraryFailure(cause);
    }

    const combinedView = new Uint8Array(combined);
    if (combinedView.length < AES_GCM_TAG_LENGTH_BYTES + 1) {
      plaintextCopy.fill(0);
      throw AeadFailedError.invalidBufferSize(
        "encrypt-output",
        AES_GCM_TAG_LENGTH_BYTES + 1,
        combinedView.length,
      );
    }
    const tagOffset = combinedView.length - AES_GCM_TAG_LENGTH_BYTES;
    const ciphertext = combinedView.slice(0, tagOffset);
    const tag = combinedView.slice(tagOffset);

    const blob = KeyValidatorBlob.create({
      expectedPlaintext: input.plaintext,
      ciphertext,
      iv,
      tag,
    });
    plaintextCopy.fill(0);
    return blob;
  }
}

function getSubtle(): webcrypto.SubtleCrypto {
  const subtle: unknown = webcrypto.subtle;
  if (typeof subtle !== "object" || subtle === null) {
    throw AeadFailedError.subtleNotAvailable();
  }
  return webcrypto.subtle;
}

function generateNonce(): Uint8Array {
  const buffer = new Uint8Array(AES_GCM_NONCE_LENGTH_BYTES);
  webcrypto.getRandomValues(buffer);
  return buffer;
}

async function importMasterKey(
  subtle: webcrypto.SubtleCrypto,
  bytes: Uint8Array,
): Promise<webcrypto.CryptoKey> {
  try {
    return await subtle.importKey(
      "raw",
      bytes,
      { name: "AES-GCM" },
      false,
      ["encrypt"],
    );
  } catch (cause: unknown) {
    throw AeadFailedError.libraryFailure(cause);
  }
}
