import { webcrypto } from "node:crypto";

import type { EnvelopeCipher } from "../../domain/services/envelope-cipher.ts";
import type { DerivedKey } from "../../domain/value-objects/derived-key.ts";
import { EncryptedMasterKey } from "../../domain/value-objects/encrypted-master-key.ts";
import { MasterKey } from "../../domain/value-objects/master-key.ts";
import { AeadFailedError } from "../errors/aead-failed-error.ts";

/**
 * Length of the AES-GCM nonce / IV, in bytes. NIST SP 800-38D
 * recommends 12 bytes (96 bits) as the canonical IV length: it lets
 * the implementation skip the GHASH-based length pre-processing and
 * matches every AEAD spec the project tolerates.
 */
const AES_GCM_NONCE_LENGTH_BYTES = 12;

/**
 * Length of the AES-GCM authentication tag, in bytes. The pin
 * (16 bytes / 128 bits) matches `EncryptedMasterKey.tagLengthBytes()`
 * and `KeyValidatorBlob` expectations. We do NOT support truncated
 * tags — truncation halves the security margin on the authenticator
 * for no measurable space gain.
 */
const AES_GCM_TAG_LENGTH_BITS = 128;
const AES_GCM_TAG_LENGTH_BYTES = AES_GCM_TAG_LENGTH_BITS / 8;

/**
 * Adapter that fulfils the `EnvelopeCipher` domain port using Node 20+
 * Web Crypto AES-256-GCM (`node:crypto` `webcrypto`).
 *
 * Why Web Crypto:
 * - Standardised, audited primitive (Node delegates to OpenSSL).
 *   Mirrors the project lineamiento §5 ("Cero implementaciones
 *   criptograficas custom"). Choosing AES-256-GCM matches
 *   `docs/06-stack-tecnico.md` §4-5 (SQLCipher v4 default cipher) —
 *   one less primitive in the trust base.
 * - Available natively on Node 20+ via `node:crypto`'s `webcrypto`
 *   namespace (`@types/node` 22 exposes the typings); no additional
 *   npm dependency.
 *
 * Output shape:
 * - `subtle.encrypt(...)` returns a single `ArrayBuffer` containing
 *   `ciphertext || tag`. The adapter splits the trailing
 *   `AES_GCM_TAG_LENGTH_BYTES` into `tag` and the rest into
 *   `ciphertext` so the resulting `EncryptedMasterKey` matches the
 *   domain VO's tri-buffer shape.
 *
 * Error contract:
 * - `wrap(...)` throws `AeadFailedError`:
 *   - `subtle-not-available` when `webcrypto.subtle` is absent.
 *   - `library-failure` for any other unexpected exception.
 * - `unwrap(...)` throws `AeadFailedError`:
 *   - `authentication-failed` when the AEAD tag does not verify.
 *     Web Crypto throws a generic `OperationError` for both wrong
 *     key and tampered ciphertext; the adapter cannot distinguish
 *     the two and folds them into `authentication-failed`.
 *   - `subtle-not-available` / `library-failure` as above.
 *
 * Security invariants:
 * - The adapter NEVER logs ciphertext, tag, IV, master key bytes or
 *   derived key bytes. The error messages carry only public metadata
 *   (lengths, kind names).
 * - The IV is freshly generated by Node's CSPRNG on every `wrap`
 *   call. Reusing an IV under the same key on AES-GCM
 *   catastrophically compromises confidentiality + authenticity, so
 *   we use `webcrypto.getRandomValues` directly here (the adapter
 *   does NOT depend on `RandomBytes` because IVs are an internal
 *   implementation concern of the AEAD primitive, not a port-level
 *   entropy concern).
 */
export class AesGcmEnvelopeCipher implements EnvelopeCipher {
  public async wrap(
    masterKey: MasterKey,
    derivedKey: DerivedKey,
  ): Promise<EncryptedMasterKey> {
    const subtle = getSubtle();
    const iv = generateNonce();

    const cryptoKey = await derivedKey.withBytes((bytes) =>
      importDerivedKey(subtle, bytes, "encrypt"),
    );

    const plaintext = masterKey.withBytes((bytes) => new Uint8Array(bytes));

    let combined: ArrayBuffer;
    try {
      combined = await subtle.encrypt(
        {
          name: "AES-GCM",
          iv,
          tagLength: AES_GCM_TAG_LENGTH_BITS,
        },
        cryptoKey,
        plaintext,
      );
    } catch (cause: unknown) {
      // Best-effort secure zero of the plaintext copy.
      plaintext.fill(0);
      throw AeadFailedError.libraryFailure(cause);
    }
    plaintext.fill(0);

    const combinedView = new Uint8Array(combined);
    if (combinedView.length < AES_GCM_TAG_LENGTH_BYTES + 1) {
      throw AeadFailedError.invalidBufferSize(
        "encrypt-output",
        AES_GCM_TAG_LENGTH_BYTES + 1,
        combinedView.length,
      );
    }
    const tagOffset = combinedView.length - AES_GCM_TAG_LENGTH_BYTES;
    const ciphertext = combinedView.slice(0, tagOffset);
    const tag = combinedView.slice(tagOffset);

    return EncryptedMasterKey.create({
      ciphertext,
      iv,
      tag,
    });
  }

  public async unwrap(
    encrypted: EncryptedMasterKey,
    derivedKey: DerivedKey,
  ): Promise<MasterKey> {
    const subtle = getSubtle();

    const cryptoKey = await derivedKey.withBytes((bytes) =>
      importDerivedKey(subtle, bytes, "decrypt"),
    );

    const ciphertext = encrypted.withCiphertext((b) => new Uint8Array(b));
    const iv = encrypted.withIv((b) => new Uint8Array(b));
    const tag = encrypted.withTag((b) => new Uint8Array(b));

    if (iv.length !== AES_GCM_NONCE_LENGTH_BYTES) {
      throw AeadFailedError.invalidBufferSize(
        "iv",
        AES_GCM_NONCE_LENGTH_BYTES,
        iv.length,
      );
    }
    if (tag.length !== AES_GCM_TAG_LENGTH_BYTES) {
      throw AeadFailedError.invalidBufferSize(
        "tag",
        AES_GCM_TAG_LENGTH_BYTES,
        tag.length,
      );
    }

    // Web Crypto expects `ciphertext || tag` concatenated.
    const combined = new Uint8Array(ciphertext.length + tag.length);
    combined.set(ciphertext, 0);
    combined.set(tag, ciphertext.length);

    let plaintextBuffer: ArrayBuffer;
    try {
      plaintextBuffer = await subtle.decrypt(
        {
          name: "AES-GCM",
          iv,
          tagLength: AES_GCM_TAG_LENGTH_BITS,
        },
        cryptoKey,
        combined,
      );
    } catch (cause: unknown) {
      // Web Crypto throws a generic `OperationError` for both
      // wrong-key and tampered-ciphertext outcomes. The contract
      // folds them into `authentication-failed`.
      throw AeadFailedError.authenticationFailed(cause);
    }

    const plaintextView = new Uint8Array(plaintextBuffer);
    if (plaintextView.length !== MasterKey.lengthBytes()) {
      // Unwrap succeeded (tag verified) but the plaintext is the
      // wrong size — only possible if the envelope ciphertext was
      // produced by a different (mismatched) routine. Treat as
      // library failure.
      throw AeadFailedError.invalidBufferSize(
        "plaintext",
        MasterKey.lengthBytes(),
        plaintextView.length,
      );
    }
    try {
      return MasterKey.from(plaintextView);
    } finally {
      plaintextView.fill(0);
    }
  }
}

/**
 * Returns Node's `webcrypto.subtle` interface, throwing a typed
 * `AeadFailedError` if the runtime does not expose it.
 */
function getSubtle(): webcrypto.SubtleCrypto {
  const subtle: unknown = webcrypto.subtle;
  if (typeof subtle !== "object" || subtle === null) {
    throw AeadFailedError.subtleNotAvailable();
  }
  return webcrypto.subtle;
}

/**
 * Generates a fresh 12-byte nonce from Node's CSPRNG. AES-GCM
 * security collapses on nonce reuse, so we use the platform's
 * canonical entropy source directly here.
 *
 * Return type is `Uint8Array<ArrayBuffer>` (not the looser
 * `Uint8Array<ArrayBufferLike>`) to document that the helper
 * always allocates a fresh `ArrayBuffer`-backed view — Web Crypto's
 * `BufferSource` accepts only `<ArrayBuffer>` under
 * `@types/node@25`'s stricter typings.
 */
function generateNonce(): Uint8Array<ArrayBuffer> {
  const buffer = new Uint8Array(AES_GCM_NONCE_LENGTH_BYTES);
  webcrypto.getRandomValues(buffer);
  return buffer;
}

/**
 * Imports the supplied 32-byte buffer as an AES-256-GCM CryptoKey.
 * The key is non-extractable so it cannot be exported back to bytes
 * by a subsequent `subtle.exportKey` call; this is defence in depth
 * against the rare case where the key handle leaks across module
 * boundaries.
 */
async function importDerivedKey(
  subtle: webcrypto.SubtleCrypto,
  bytes: Uint8Array<ArrayBuffer>,
  usage: webcrypto.KeyUsage,
): Promise<webcrypto.CryptoKey> {
  try {
    return await subtle.importKey(
      "raw",
      bytes,
      { name: "AES-GCM" },
      false,
      [usage],
    );
  } catch (cause: unknown) {
    throw AeadFailedError.libraryFailure(cause);
  }
}
